/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model;

import java.awt.ComponentOrientation;

/**
 *
 * @author Giu
 */
public class Tela_Principal extends javax.swing.JFrame {
    
    //Atributos da classe Moeda
    Moeda cofre = null;
    Moeda cofre2 = null;
    
    /**
     * Creates new form Tela_Principal
     */
    public Tela_Principal() {
        initComponents();
        setLocationRelativeTo(null);
        //jTextArea_Resultado.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        jButton_Adicionar.setEnabled(false);
        jButton_Adicionar2.setEnabled(false);
        jTextArea_Resultado.setEnabled(false);
        jTextField_1Cent.setEnabled(false);
        jTextField_5Cent.setEnabled(false);
        jTextField_10Cent.setEnabled(false);
        jTextField_25Cent.setEnabled(false);
        jTextField_50Cent.setEnabled(false);
        jTextField_1Real.setEnabled(false);
    }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField_1Cent = new javax.swing.JTextField();
        jTextField_5Cent = new javax.swing.JTextField();
        jTextField_10Cent = new javax.swing.JTextField();
        jTextField_25Cent = new javax.swing.JTextField();
        jTextField_50Cent = new javax.swing.JTextField();
        jTextField_1Real = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_Resultado = new javax.swing.JTextArea();
        jButton_Adicionar = new javax.swing.JButton();
        jButton_Criar = new javax.swing.JButton();
        jButton_Adicionar2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Cofre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("R$ 0.01");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("R$ 0.05");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("R$ 0.10");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("R$ 0.25");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("R$ 0.50");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("R$ 1.00");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Quantas moedas você deseja adicionar no Cofre ?");

        jTextArea_Resultado.setBackground(new java.awt.Color(230, 228, 228));
        jTextArea_Resultado.setColumns(20);
        jTextArea_Resultado.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jTextArea_Resultado.setRows(5);
        jScrollPane1.setViewportView(jTextArea_Resultado);

        jButton_Adicionar.setBackground(new java.awt.Color(204, 204, 204));
        jButton_Adicionar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Adicionar.setText("Adicionar 1");
        jButton_Adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AdicionarActionPerformed(evt);
            }
        });

        jButton_Criar.setBackground(new java.awt.Color(204, 204, 204));
        jButton_Criar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Criar.setText("Criar Cofre");
        jButton_Criar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CriarActionPerformed(evt);
            }
        });

        jButton_Adicionar2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Adicionar2.setText("Adicionar 2");
        jButton_Adicionar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Adicionar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_1Cent)
                            .addComponent(jTextField_5Cent)
                            .addComponent(jTextField_10Cent)
                            .addComponent(jTextField_25Cent)
                            .addComponent(jTextField_50Cent)
                            .addComponent(jTextField_1Real)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton_Adicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_Adicionar2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jButton_Criar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_1Cent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Criar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField_5Cent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField_10Cent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField_25Cent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField_50Cent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField_1Real, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_Adicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_Adicionar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_CriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CriarActionPerformed
        // TODO add your handling code here:
        cofre = Moeda.getCofre("Cofre de Moedas\n");
        cofre2 = Moeda.getCofre("Cofre de Moedas\n");
        
        jButton_Adicionar.setEnabled(true);
        jButton_Adicionar2.setEnabled(true);
        jTextArea_Resultado.setEnabled(true);
        jTextField_1Cent.setEnabled(true);
        jTextField_5Cent.setEnabled(true);
        jTextField_10Cent.setEnabled(true);
        jTextField_25Cent.setEnabled(true);
        jTextField_50Cent.setEnabled(true);
        jTextField_1Real.setEnabled(true);
        
        jButton_Criar.setEnabled(false);
    }//GEN-LAST:event_jButton_CriarActionPerformed

    private void jButton_AdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AdicionarActionPerformed
        // TODO add your handling code here:
        //Moeda moeda_cofre = new Moeda(String titulo);
                   
        /*String entrada = "";
        entrada = jTextField_1Cent.getText();
        cofre.setUm_centavo(Integer.parseInt(entrada));
        
        entrada = jTextField_5Cent.getText();
        cofre.setCinco_centavos(Integer.parseInt(entrada));
        
        entrada = jTextField_10Cent.getText();
        cofre.setDez_centavos(Integer.parseInt(entrada));
        
        entrada = jTextField_25Cent.getText();
        cofre.setVinte_e_cinco_centavos(Integer.parseInt(entrada));
        
        entrada = jTextField_50Cent.getText();
        cofre.setCinquenta_centavos(Integer.parseInt(entrada));
        
        entrada = jTextField_1Real.getText();
        cofre.setUm_real(Integer.parseInt(entrada));
        
        String saida_moedas_cofre = "Cofre de Moedas \n\n";
        saida_moedas_cofre += "Quantidade de Moedas " +"\n";
        saida_moedas_cofre += "R$ 0.01 : " + jTextField_1Cent.getText() + "\n";
        saida_moedas_cofre += "R$ 0.05 : " + jTextField_5Cent.getText() + "\n";
        saida_moedas_cofre += "R$ 0.10 : " + jTextField_10Cent.getText() + "\n";
        saida_moedas_cofre += "R$ 0.25 : " + jTextField_25Cent.getText() + "\n";
        saida_moedas_cofre += "R$ 0.50 : " + jTextField_50Cent.getText() + "\n";
        saida_moedas_cofre += "R$ 1.00 : " + jTextField_1Real.getText() + "\n";
        saida_moedas_cofre += "\nTotal de Moedas Adicionadas : " + cofre.ContarMoedas() + "\n";
        saida_moedas_cofre += "Valor Total Adicionado - R$ : " + cofre.TotalMoedas() + "\n";
        
        jTextArea_Resultado.setText(saida_moedas_cofre);*/
        
        cofre.setUm_centavo(Integer.parseInt(jTextField_1Cent.getText()));
        jTextArea_Resultado.setText(Integer.toString(cofre.get1Cent()));
        
        cofre.setUm_centavo(Integer.parseInt(jTextField_5Cent.getText()));
        jTextArea_Resultado.setText(Integer.toString(cofre.get5Cent()));
        
        cofre.setUm_centavo(Integer.parseInt(jTextField_10Cent.getText()));
        jTextArea_Resultado.setText(Integer.toString(cofre.get10Cent()));
        
        cofre.setUm_centavo(Integer.parseInt(jTextField_25Cent.getText()));
        jTextArea_Resultado.setText(Integer.toString(cofre.get25Cent()));
        
        cofre.setUm_centavo(Integer.parseInt(jTextField_50Cent.getText()));
        jTextArea_Resultado.setText(Integer.toString(cofre.get50Cent()));
        
        cofre.setUm_centavo(Integer.parseInt(jTextField_1Real.getText()));
        jTextArea_Resultado.setText(Integer.toString(cofre.get1Real()));
         
        jTextArea_Resultado.setText(Integer.toString(cofre.ContarMoedas()));
        
        //jTextArea_Resultado.setText(Float.toString(cofre.TotalMoedas()));
        
        jTextField_1Cent.setText("");
        jTextField_5Cent.setText("");
        jTextField_10Cent.setText("");
        jTextField_25Cent.setText("");
        jTextField_50Cent.setText("");
        jTextField_1Real.setText("");
        
    }//GEN-LAST:event_jButton_AdicionarActionPerformed

    private void jButton_Adicionar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Adicionar2ActionPerformed
        // TODO add your handling code here:
        cofre2.setUm_centavo(Integer.parseInt(jTextField_1Cent.getText()));
        jTextArea_Resultado.setText(Integer.toString(cofre2.get1Cent()));
        
        cofre2.setUm_centavo(Integer.parseInt(jTextField_5Cent.getText()));
        jTextArea_Resultado.setText(Integer.toString(cofre2.get5Cent()));
        
        cofre2.setUm_centavo(Integer.parseInt(jTextField_10Cent.getText()));
        jTextArea_Resultado.setText(Integer.toString(cofre2.get10Cent()));
        
        cofre2.setUm_centavo(Integer.parseInt(jTextField_25Cent.getText()));
        jTextArea_Resultado.setText(Integer.toString(cofre2.get25Cent()));
        
        cofre2.setUm_centavo(Integer.parseInt(jTextField_50Cent.getText()));
        jTextArea_Resultado.setText(Integer.toString(cofre2.get50Cent()));
        
        cofre2.setUm_centavo(Integer.parseInt(jTextField_1Real.getText()));
        jTextArea_Resultado.setText(Integer.toString(cofre2.get1Real()));
         
        jTextArea_Resultado.setText(Integer.toString(cofre2.ContarMoedas()));
        
        //jTextArea_Resultado.setText(Float.toString(cofre.TotalMoedas()));
        
        jTextField_1Cent.setText("");
        jTextField_5Cent.setText("");
        jTextField_10Cent.setText("");
        jTextField_25Cent.setText("");
        jTextField_50Cent.setText("");
        jTextField_1Real.setText("");
    }//GEN-LAST:event_jButton_Adicionar2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Adicionar;
    private javax.swing.JButton jButton_Adicionar2;
    private javax.swing.JButton jButton_Criar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_Resultado;
    private javax.swing.JTextField jTextField_10Cent;
    private javax.swing.JTextField jTextField_1Cent;
    private javax.swing.JTextField jTextField_1Real;
    private javax.swing.JTextField jTextField_25Cent;
    private javax.swing.JTextField jTextField_50Cent;
    private javax.swing.JTextField jTextField_5Cent;
    // End of variables declaration//GEN-END:variables
}
